### ISSUE TITLE
Main.js missing

### ISSUE THREAD

**Issue by huachuman** [zweek/commentesque-footnotes#1]
Hey there, I just stumbled upon this plugin browsing github and this looks really amazing and seems to do what I wish other footnote plugins did. 

But I'm not able to install, BRAT is telling me it's missing the main.js. 

What do?

**Comment by zweek** [comment]
oop yeah that'll be because I haven't made a proper release for this plugin yet so you would've had to build the main.js from the typescript files with npm BUT [i've now made a release](https://github.com/zweek/commentesque-footnotes/releases/tag/1.0.0) so you can give it a try now if you want :]

it should work if you put those files directly into a folder structure like `.obsidian/plugins/commentesque-footnotes/` and then enable it from within obsidian in the community plugins tab
